#!/usr/bin/env ruby

module UTCnow

	def self.pbcopy(input)
	  str = input.to_s
	  IO.popen('pbcopy', 'w') { |f| f << str }
	  puts 'Copied!'
	end

	t = Time.now.utc.strftime("%F %T")

  pbcopy(t)

end
